{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ids-api.fullname" . }}
  labels:
    {{- include "ids-api.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                {{- if eq .Values.deploymentStrategy "canary" }}
                name: {{ include "ids-api.fullname" . }}-stable
                {{- else }}
                name: {{ include "ids-api.fullname" . }}
                {{- end }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
