apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ids-api.fullname" . }}-secrets
  labels:
    {{- include "ids-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DAGSHUB_USER: {{ .Values.secrets.dagshubUser | quote }}
  DAGSHUB_TOKEN: {{ .Values.secrets.dagshubToken | quote }}
  MLFLOW_TRACKING_USERNAME: {{ .Values.secrets.mlflowUser | quote }}
  MLFLOW_TRACKING_PASSWORD: {{ .Values.secrets.mlflowPassword | quote }}
